#!/usr/bin/env python

import os
import sys

cmd_H_cd_cn = 'git --no-pager log --pretty="format:%H;%cd;%cn" -n1'
cmd_tag = 'git --no-pager describe'
cmd_branch = 'git --no-pager branch | grep \*'

def exec_ret(command):
	f = os.popen(command, 'r')
	r = f.read()
	f.close()
	return r

h, cd, cn =  exec_ret(cmd_H_cd_cn).split(';')
tag = exec_ret(cmd_tag)[:-1]
branch = exec_ret(cmd_branch)[2:-1]

if len(sys.argv) == 1:
	f = sys.stdout
elif len(sys.argv) != 2:
	print 'install <path to config.release.php>'
	sys.exit()
else:
	f = open(sys.argv[1], 'w')

f.write("<?\n"+
	"if(!isset($cfg['release'])) $cfg['release'] = array();\n"+
	"$cfg['release']['hash'] = '%s';\n" % h +
	"$cfg['release']['date'] = '%s';\n" % cd +
	"$cfg['release']['by'] = '%s';\n" % cn +
	"$cfg['release']['tag'] = '%s';\n" % tag +
	"$cfg['release']['branch'] = '%s';\n" % branch +
	"?>")

if f != sys.stdout:
	f.close()
