#!/usr/bin/env python

import os
import sys
import locale

try:
	# Nederlandse afkortingen voor data
	locale.setlocale(locale.LC_ALL, 'nl_NL')
except Exception:
	pass

cmd_H_ct_cn = 'git --no-pager log --pretty="format:%H;%ct;%cn" -n1'
cmd_tag = 'git --no-pager describe'
cmd_branch = 'git --no-pager branch | grep \*'

def exec_ret(command):
	f = os.popen(command, 'r')
	r = f.read()
	f.close()
	return r

h, ct, cn =  exec_ret(cmd_H_ct_cn).split(';')
tag = exec_ret(cmd_tag)[:-1]
branch = exec_ret(cmd_branch)[2:-1]

if len(sys.argv) == 1:
	f = sys.stdout
elif len(sys.argv) != 2:
	print 'install <path to config.release.php>'
	sys.exit()
else:
	f = open(sys.argv[1], 'w')

f.write("<?php\n"+
	"if(!isset($cfg['release'])) $cfg['release'] = array();\n"+
	"$cfg['release']['hash'] = '%s';\n" % h +
	"$cfg['release']['date'] = '%s';\n" % ct +
	"$cfg['release']['by'] = '%s';\n" % cn +
	"$cfg['release']['tag'] = '%s';\n" % tag +
	"$cfg['release']['branch'] = '%s';\n" % branch +
	"$cfg['bgs'] = array(\n")

had = set()
first = True
for i in os.listdir('img/bgs'):
	if i[-4:] != '.png':
		continue
	bits = i.split('.')
	if len(bits) < 3:
		continue
	n = '.'.join(bits[1:])
	if n in had:
		continue
	if first: first = False
	else: f.write(',\n')
	f.write("  '%s'" % n)
	had.add(n)

f.write("\n);\n"+
	"?>")

if f != sys.stdout:
	f.close()
