#!/bin/bash
git push --all --receive-pack=/www/karpenok/bin/git-receive-pack ssh://karpenok@galeras.uci.kun.nl/www/karpenok/webdocs 

git push --tags --receive-pack=/www/karpenok/bin/git-receive-pack ssh://karpenok@galeras.uci.kun.nl/www/karpenok/webdocs 

ssh karpenok@galeras.uci.kun.nl 'source /etc/profile; cd webdocs; git checkout -f; utils/install config.release.php'
